# Generated by Django 5.0.2 on 2024-02-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waving', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wave_send',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
