# Generated by Django 5.0.2 on 2024-02-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('personal_quotes', models.CharField(max_length=100)),
                ('interests', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=200)),
                ('picture', models.CharField(max_length=100)),
                ('residence', models.CharField(max_length=100)),
                ('wave_buddy', models.CharField(max_length=100)),
            ],
        ),
    ]
