# Generated by Django 5.0.2 on 2024-02-20 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('personal_quotes', models.CharField(max_length=100)),
                ('interests', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=200)),
                ('picture', models.CharField(max_length=100)),
                ('residence', models.CharField(max_length=100)),
                ('wave_buddy', models.CharField(max_length=100)),
                ('connections', models.ManyToManyField(blank=True, to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Wave_Send',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('from_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_waves', to='profiles.profile')),
                ('to_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_waves', to='profiles.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='received_requests',
            field=models.ManyToManyField(blank=True, related_name='received_wave_requests', through='profiles.Wave_Send', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sent_requests',
            field=models.ManyToManyField(blank=True, related_name='sent_wave_requests', through='profiles.Wave_Send', to='profiles.profile'),
        ),
    ]
