# Generated by Django 5.0.3 on 2024-03-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_password_alter_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.CharField(default='z', max_length=150),
            preserve_default=False,
        ),
    ]
